###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8090
spring.application.name: backend-service

websocket-client:
  broker-url: ws://localhost:8080/stomp
  inbound-topics:
    - "/topic/greetings"
  outbound-topics:
    - "/server/test"

redis-client:
  outbound-topics: "TOAST_MESSAGE"
  inbound-topics: "GREETINGS"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.info.enabled: true

spring:
  redis:
    host: localhost   # Redis Server Host
    port: 6379        # Redis Server Port
    ssl: false        # Enable SSL support
    database: 0       # database index