###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8090
spring.application.name: backend-service

websocket-client:
  broker-url: ws://localhost:8080/stomp
  inbound-topics: "/topic/greetings"

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.info.enabled: true
