###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8080
spring.application.name: notification-service

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.info.enabled: true