###############################################################################################
# Server Configuration
###############################################################################################

server.port: 8080
spring.application.name: websocket-stomp-server

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: INFO
    org.springframework.security: INFO
    com.example.notification: DEBUG

management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint.info.enabled: true

#amqp.config:
#  mqURL: localhost:5672
#  mqUsername: guest
#  mqPassword: guest

spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
